### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by robus9one** [42Kmi/LagDrop#3]
Hello, my problem is that after installing, the lagdropcount.sh script does not show any numbers. Blocked and transmitted connections always indicate zero. I suspect that it does not work with me. I tested the computer and console IP, the same results. I did everything according to the instructions.

Can you tell me which version of DD-WRT your script was working on? I installed the latest and 
DD-WRT v24-sp2 (05/06/15) std. Both have the same results.

I tested three versions of your software, 2.0.8, 2.0.5 and 1.7.8.

The second thing is that there are errors: "Permission denied".

I play a lot in FIFA and I need your tool like water.

What can I do in this situation? Please help. Regards!

PS. My device is Asus RT-N18U.

**Comment by 42Kmi** [comment]
Hey,
Thanks for downloading LagDrop. I'm relying to let you know I saw your
message. I'll reply later with a more substantial response to help you set
things up. Currently studying for an exam.

**Comment by 42Kmi** [comment]
Hello,
Sorry for the late reply. I've been super busy with med school.

I'm running DD-WRT v24-sp2 (02/04/15) std on a Buffalo WZR-HP-G300NH. I'm
not sure what changes have been made to DD-WRT since I uploaded the version
of LagDrop currently available at lagdrop.com, but I've been working on the
latest yet-to-be-released version for some time now. I haven't uploaded yet
since I've been busy with school, but I can try to upload it when I get a
chance.

Thanks for checking out LagDrop. I hope I can help you get it working
properly. It's awesome when it works,

**Comment by robus9one** [comment]
I'm happy to wait, no hurry.

I keep my fingers crossed for you, good luck!

**Comment by 42Kmi** [comment]
I just pushed the Version 3.0.0 beta. Please check it out.

**Comment by robus9one** [comment]
Hello! I installed everything according to your instructions. I had a few problems, a few unresolved.

The first problem is chmod 755- it did not create a 42Kmi folder. I had to set it to 777- it works.

The second problem concerns the command sh / jffs/lagdrop.sh "xbox". After starting, the 42Kmi folder and the options file appear. There is also a report that I attach in the picture.
![log after instalation](https://user-images.githubusercontent.com/39467381/40576947-45824c5c-60fe-11e8-98d6-9f571224b23f.jpg)

The third problem is for the lagdropcount.sh application. To check it, I threw the computer ip. The application starts, but it looks like in the second picture.
![lagdropcountsh](https://user-images.githubusercontent.com/39467381/40576966-85b74a2a-60fe-11e8-89c1-7bfa869d3e31.jpg)

I suspect that your program still does not work for me. 

Regards!

**Comment by 42Kmi** [comment]
Thanks. There was a mistake with the Xbox filter. If you noticed where it
said echo, I forgot to put a space there.

I just fixed that and removed the egrep command and just pushed an update.
Please test. Thanks again

**Comment by robus9one** [comment]
Now it's 

/jffs/lagdrop.sh: line 534: divide by zero
/jffs/lagdrop.sh: line 534: : Permission denied
Chain LDREJECT (1 references)
target     prot opt source               destination         
Chain LDBAN (1 references)
target     prot opt source               destination         
/jffs/lagdrop.sh: line 534: sentinel: not found
Killed
/jffs/lagdrop.sh: line 534: divide by zero
/jffs/lagdrop.sh: line 534: : Permission denied
/jffs/lagdrop.sh: line 534: sentinel: not found
Killed

and lagdropcount.sh doesn't any change...

**Comment by 42Kmi** [comment]
Could you send a pic of your options.txt file?
The divide by zero error maybe be a normal function if your system is on
and you haven't connected to any peers.

LagDrop takes averages of ping times, etc, so if there aren't any detected,
then it will result in a 0. I can try fixing this though.

You can check this by going to the options.txt file, confirm that there is
an IP address there in the first line. You can test by changing the IP
address to your PC's IP address and browsing the internet (write it as
PC_IP_ADDRESS#CONSOLE_IP_ADDRESS for ease, since LagDrop ignores everything
on the line after a #)

Thanks again

**Comment by robus9one** [comment]
xbox=192.168.1.109
PINGLIMIT=20
COUNT=20
SIZE=2048
MODE=1
MAXTTL=20
PROBES=5
TRACELIMIT=30
ACTION=REJECT
CHECKPACKETLOSS=OFF
PACKETLOSSLIMIT=10
SENTINEL=OFF
CLEARALLOWED=OFF
CLEARBLOCKED=OFF
CLEARLIMIT=10
CHECKPORTS=NO
PORTS=
RESTONMULTIPLAYER=NO
NUMBEROFPEERS=
DECONGEST=OFF
SWITCH=ON
;

I also tried to find an opponent in FIFA, and found a visitor with a poor connection. I have no idea what to do about it. I do not know about these lines and software, I only do as you describe it, I test it and it does not work.

I am sorry that you have such problems with me.

I also tried to insert the computer's IP in front of #, in the passed and blocked nothing appears, nothing but zeros.

**Comment by 42Kmi** [comment]
Show me what you wrote to execute LagDrop and where. Thanks

**Comment by 42Kmi** [comment]
Is your Xbox set to a static IP address?

**Comment by robus9one** [comment]
![zrzut ekranu 25](https://user-images.githubusercontent.com/39467381/40580295-e690ecc4-613b-11e8-9112-5b6d1adde5e4.png)
![zrzut ekranu 26](https://user-images.githubusercontent.com/39467381/40580298-e8bf790c-613b-11e8-83ea-92025c46cce5.png)
![zrzut ekranu 27](https://user-images.githubusercontent.com/39467381/40580299-eb39d9e8-613b-11e8-8643-7d7ba5277a6c.png)
![zrzut ekranu 28](https://user-images.githubusercontent.com/39467381/40580301-ed8739d4-613b-11e8-9e25-2afe1fba06de.png)
![zrzut ekranu 29](https://user-images.githubusercontent.com/39467381/40580302-ef952cea-613b-11e8-8d3b-c3c0a2d92a9a.png)
![zrzut ekranu 30](https://user-images.githubusercontent.com/39467381/40580304-f17c8eb8-613b-11e8-949e-10ee9d5621bb.png)
![zrzut ekranu 31](https://user-images.githubusercontent.com/39467381/40580306-f33486e8-613b-11e8-8dbf-68b6ae67b2b5.png)

Hello, static IP for XBOX set.

After inserting the script into the command shell and setting up access 755, nothing happened. It's only when I put 777 that the 42Kmi folder and the options file are created automatically, without a command shell.

With tests still 0 passed and 0 blocked, this is impossible because in the online seasons in league 1 in FIFA I always have lags, and there is a P2P connection.

**Comment by 42Kmi** [comment]
To the end of the line in cronjobs, add &> /dev/null

Also included that when running LagDrop

In command shell in administration > commands, try running the command ps a
few times to see that lagdrop.sh is running.

ps will display the running processes on your router

**Comment by 42Kmi** [comment]
Hello again.
I fixed many more errors that I recently found. I have updated LagDrop, so
please test it. Hopefully it should work for you now.

Thank again

**Comment by robus9one** [comment]
Everything has been installed beautifully.

However, when I launch the lagdropclear.sh application, I still do not have any data about passed and blocked players.

I give up, greetings and thank you for your help!

**Comment by 42Kmi** [comment]
lagdropclear.sh will clear all the blocked and accepted players, so you
wouldn't see anything.
lagdropcount.sh will show you a count of the blocked and accepted players

**Comment by robus9one** [comment]
Ohhh sorry I mean lagdropcount.sh.

I have a different option, I think about geoip and allow only Europe or Poland and Germany. I'm FIFA player, so this is good idea.

**Comment by 42Kmi** [comment]
If it works for you that is fine too. If you want, you could try
downgrading your DD-WRT to the version I'm using, since my version
definitely works with LagDrop. I'll continue working on it.
Thanks for your interest in LagDrop. I was able to make significant
improvements to how it works in the past few days.
